### ISSUE TITLE
PHAR 3.3.0 has \r char that breaks tool under Linux

### ISSUE THREAD

**Issue by Slamdunk** [maglnet/ComposerRequireChecker#281]
See https://github.com/shivammathur/setup-php/issues/473#issuecomment-878098357

```console
$ wget "https://github.com/maglnet/ComposerRequireChecker/releases/download/3.3.0/composer-require-checker.phar"
[...]
2021-07-12 11:17:18 (1.38 MB/s) - ‘composer-require-checker.phar’ saved [634200/634200]
$ chmod +x composer-require-checker.phar
$ ./composer-require-checker.phar
/usr/bin/env: ‘php\r’: No such file or directory
```

**Comment by Slamdunk** [comment]
Likely related to https://github.com/maglnet/ComposerRequireChecker/blob/a4a03806b5fd4c11f04fcb48c2accde877dc9bd1/build.xml#L60

**Comment by loevgaard** [comment]
Obviously I don't know what people use for setting up their CI, but I use GitHub Actions and https://github.com/shivammathur/setup-php for setting up PHP. I have fixed this temporarily with this setup-php config:

```yaml
dependency-analysis:
    name: "Dependency Analysis"

    runs-on: "ubuntu-latest"

    strategy:
        matrix:
            php-version:
                - "7.4"
                - "8.0"

            dependencies:
                - "highest"

    steps:
        -   name: "Checkout"
            uses: "actions/checkout@v2"

        -   name: "Setup PHP, with composer and extensions"
            uses: "shivammathur/setup-php@v2"
            with:
                coverage: "none"
                extensions: "${{ env.PHP_EXTENSIONS }}"
                php-version: "${{ matrix.php-version }}"
                tools: "composer-require-checker:3.1.0, composer-unused" # todo using 3.1.0 until this issue is fixed: https://github.com/maglnet/ComposerRequireChecker/issues/281
```

Notice the `composer-require-checker:3.1.0` in the `tools` key.
