### ISSUE TITLE
Cache execution results so that subsequent calls are processed faster

### ISSUE THREAD

**Issue by maks-rafalko** [maglnet/ComposerRequireChecker#295]
Many dev tools are using cache files (e.g. PHPCSFixer, PHPUnit, PHPStan, Psalm, Deptrac and others), giving us performance boost locally and on CI. Look at this image, where the first run is without cache, and the second run is with cache files used for dev tools:

![image](https://user-images.githubusercontent.com/3725595/129959103-5d303870-04f0-4d98-969d-5f2b6b06c613.png)

As you can see, caching can save us minutes or tens of minutes, depending on the project size (as an example, look at the PHP Code Style column, which is PHPCSFixer, that saves 3m 43s with cache being used.

On the other side, please look at the "Check Required Packages" column, where cache is not used - it always takes ~1m, which is too much.

Is it possible to introduce some level of caching, and for example check only changed files?

If this feature is going to be implemented, please consider have an option to define where the cache file should be located, like:

```
--cache-file=custom/path/to/cache/.php_cs.cache
```

**Comment by DanielBadura** [comment]
Increase peformance via caching sound quite nice. An option to deactivate the cache should be implemented with it i think.

**Comment by Ocramius** [comment]
Reminder that there are two complex problems in computer science:

 * naming
 * caching
 * off by one errors

This tool is very very minimal, compared to others, and it's supposed to mostly run in CI (where caching is unavailable), so I'd say "avoid unless demonstrated to make a real difference".

As a side-note, I run `vimeo/psalm` exclusively with `--no-cache` these days, as it became basically unusable when having the cache enabled.

**Comment by DanielBadura** [comment]
> This tool is very very minimal, compared to others, and it's supposed to mostly run in CI (where caching is unavailable)

Sure, i prefer often to run tools also local but i see your point here.

> As a side-note, I run vimeo/psalm exclusively with --no-cache these days, as it became basically unusable when having the cache enabled.

Kinda true tbh, i need to bust the cache more often then i would like it.

**Comment by ruudk** [comment]
> and it's supposed to mostly run in CI (where caching is unavailable),

We run a lot of tools on CI with caching, like Composer dependencies, PHPStan results, PHP-CS-Fixer cache etc. This works great and gives us a speed improvements.

FWIW, `ComposerRequireChecker` takes 5 minutes and 30 seconds on our GitHub Actions pipeline. We run a very large monolith with 10k classes, that might cause the slowness. But this is the slowest job.

**Comment by Ocramius** [comment]
5m30s for a 10k classes structure is acceptable, IMO 

Even then, remember that there are two difficult problems in software: naming things, caching and off by one errors. Caching must be a necessity, before being introduced, and not a "nice to have"

**Comment by ruudk** [comment]
Created a PR: 
- https://github.com/maglnet/ComposerRequireChecker/pull/344

**Comment by ruudk** [comment]
After creating a caching layer in #344 I thought, how can I make this faster?

I noticed 2 things in my setup:

1) I use `shivammathur/setup-php` and did not set `coverage: none`. By default, it runs everything with `xdebug` enabled. This change alone already shaved off minutes!

2) I thought this CLI would be perfect for JIT, so I tried to run it with `ini-values: opcache.enable_cli=1, opcache.jit=tracing, opcache.jit_buffer_size=64M` and now it runs in 37 seconds!

This is my configuration:
```yaml
 composer-require-checker:
        runs-on: ubuntu-20.04
        steps:
            -  name: Checkout
                uses: actions/checkout@v2.4.0
            -  name: Setup PHP
                id: setup-php
                uses: shivammathur/setup-php@2.16.0
                with:
                    php-version: '8.0'
                    coverage: none
                    tools: composer-require-checker
                    ini-values: opcache.enable_cli=1, opcache.jit=tracing, opcache.jit_buffer_size=64M
            -   uses: ramsey/composer-install@1.3.0
            -   name: Check dependencies
                 run: composer-require-checker check --config-file=.composer-require-checker.json
```

The cache from #344 runs 18 seconds faster, 19 seconds in total. 

@Ocramius Is this worth the complexity? I guess not.

Maybe we can update the readme that explain the JIT trick. And maybe we can add a warning when the command is executed when xdebug is enabled. Then, the caching layer PR can be closed.
